'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On
Imports Microsoft.Extensions.Configuration
'Namespace My

'    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
'     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),
'     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
'    Partial Friend NotInheritable Class MySettings
'        Inherits Global.System.Configuration.ApplicationSettingsBase

'        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

'#Region "Funzionalità di salvataggio automatico My.Settings"
'#If _MyType = "WindowsForms" Then
'        Private Shared addedHandler As Boolean

'        Private Shared addedHandlerLockObject As New Object

'        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
'        Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
'            If My.Application.SaveMySettingsOnExit Then
'                My.Settings.Save()
'            End If
'        End Sub
'#End If
'#End Region

'        Public Shared ReadOnly Property [Default]() As MySettings
'            Get

'#If _MyType = "WindowsForms" Then
'                If Not addedHandler Then
'                    SyncLock addedHandlerLockObject
'                        If Not addedHandler Then
'                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
'                            addedHandler = True
'                        End If
'                    End SyncLock
'                End If
'#End If
'                Return defaultInstance
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
'         Global.System.Configuration.DefaultSettingValueAttribute("Driver={MySQL ODBC 5.3 Unicode Driver};server=pulizieuffici.biz;uid=pegaso;databa" &
'            "se=cesar;port=3307;pwd=Ilmitodelpulito1!;Charset=utf8;")>
'        Public ReadOnly Property imp_est() As String
'            Get
'                Return CType(Me("imp_est"), String)
'            End Get
'        End Property
'    End Class
'End Namespace
Namespace My
    Partial Friend NotInheritable Class MySettings
        Private Shared _configuration As IConfiguration
        Private Shared _defaultInstance As MySettings

        Shared Sub New()
            Dim builder As New ConfigurationBuilder()
            builder.SetBasePath(System.AppDomain.CurrentDomain.BaseDirectory)
            builder.AddJsonFile("jsConfigurazione.json") ' Specifica il tuo file di configurazione
            _configuration = builder.Build()
            _defaultInstance = New MySettings()
        End Sub

        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                Return _defaultInstance
            End Get
        End Property

        Public ReadOnly Property imp_est() As String
            Get
                Return _configuration.GetSection("MySettings")("imp_est")
            End Get
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.PoP2._0.My.MySettings
            Get
                Return Global.PoP2._0.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
